### ISSUE TITLE
How do I remove this?

### ISSUE THREAD

**Issue by themightyoarfish** [manilarome/thunderblur#6]
The install unfortunately renders my TB almost unusable. What steps need I take to revert back to my previous settings?

**Comment by themightyoarfish** [comment]
I reverted the  `chrome` directory and reverted the Theme setting in Firefox, but the changes are still there.

**Comment by eromatiya** [comment]
If you used the install script, find the user.js in your profile then delete
it.

**Comment by themightyoarfish** [comment]
Nevermind, the  copy of `chrome` i had was from a previous install. So removing or restoring it properly removes the changes.
